export const ALPHABETS = {
  it: 'ABCDEFGHILMNOPQRSTUVZ',
  en: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
};

// Liste comuni di parole per Impiccato, Anagrammi e Word Ladder.
// Italiano: solo lettere dell'alfabeto italiano (no J/K/W/X/Y) e nessun accento.
export const WORDS = {
  it: [
    // 3 lettere
    'uno','due','tre','sei','mai','ago','ape','oca','uva','eco','era','ora','oro','mio','tuo','suo','lui','noi','voi','sud','dei','dea','re','ali','arte',
    // 4 lettere
    'alba','alga','alto','anca','anni','anno','ansa','ante','arco','area','arte','arti','asma','asse','asso','asta','aste','atto','aula','aura','auto',
    'bara','base','bava','bene','bere','bevi','bevo','bici','biga','boia','bolo','bora','bove','buca','buco','buoi',
    'cala','calo','came','cane','cani','capi','capo','cara','care','caro','casa','case','caso','cava','cavi','cavo','ceci','cede','cedi','cedo','cena','cene','ceno','cero','ciao','cibi','cibo','cima','cime','cita','citi','cito','code','coda','cola','colo','come','cono','cori','coro','cosa','cose','cubi','cubo','cura','cure','curo',
    'dado','dadi','dama','dame','dare','date','dato','deve','devi','devo','dice','dici','dico','dita','dito','divi','divo','doge','doma','domi','domo','doni','dono','dose','dosi','dote','doti','dove','duca','duce',
    'ecco','ente','enti','eroe','eroi','esca','esce','esci','esco','etto',
    'fame','fare','fari','faro','fase','fasi','fata','fate','fato','fava','fede','fida','fido','fila','fili','filo','fine','fini','fino','foca','foci','foro','foto','fumo','fune','funi',
    'gala','gale','gelo','gita','gite','godi','godo','gola','gole','gota','gote','guai',
    'idea','idee','ieri','iena','iene','inno',
    'lago','lana','lane','lava','lave','lavo','lega','lego','lena','leva','leve','levo','lima','limi','limo','lino','lira','lire','lite','liti','lobo','lode','lodi','loro','luna','lune','lupa','lupi','lupo','luce','luci',
    'male','mali','mano','mani','mare','mari','mela','mele','melo','mena','meno','mese','mesi','meta','mete','mira','mire','miti','mito','moda','mode','modi','modo','mola','mole','molo','mora','more','mori','moro','moto','muco','mura','muri','muro','musa','muse','muso','muta','mute','muto',
    'nani','nano','nasi','naso','nata','nate','nati','nato','nave','navi','nera','nere','nero','neve','nevi','nido','nidi','noce','noci','nodi','nodo','noia','noie','nome','nomi','nono','nord','nota','note','nove','nube','nubi','nuca','nuda','nude','nudi','nudo',
    'oboe','odio','oggi','ogni','olio','olmi','olmo','onda','onde','orsi','orso','orto','orzo','ossi','osso','oste','otto',
    'pace','paci','paga','pago','pala','pale','palo','pane','pani','papa','para','pari','paro','peli','pelo','pena','pene','pera','pere','peso','pesi','pino','pini','pipa','pipe','poco','polo','pomo','pori','poro','posa','posi','poso','pura','pure','puro',
    'radi','rado','rami','ramo','rara','rare','raro','raso','rete','reti','rido','riti','riva','rive','rivo','rosa','rose','roso','rovo','ruba','rude','rudi','ruga',
    'sala','sale','sana','sane','sani','sano','sega','seme','semi','seno','sera','sere','seta','sete','sodi','sodo','sole','soli','solo','sugo',
    'tace','taci','tale','tali','tana','tane','tata','tate','tema','teme','temi','tese','tesi','teso','tipi','tipo','tira','tiri','tiro','tisi','tomi','tomo','toni','tono','topi','topo','tubo','tuoi',
    'urlo','urli','urna','urne','urto','urti',
    'vado','vaga','vago','vale','vali','vano','vasi','vaso','vela','vele','vena','vene','vere','veri','vero','vile','vili','vino','vita','vite','viva','vive','vivi','vivo','voce','voci','voga','vola','voli','volo','voto','voti','vuoi',
    'zero','zona','zone',
    // 5 lettere
    'aceto','aiuto','albio','altro','altra','altre','altri','amare','amavo','amato','amica','amico','amore','andai','anche','angeli','anima','apice','arare','arena','aroma','arrivo','asino','astio','atomo','attiva','autostrada','autori','avere','avevo','avuto',
    'bacca','bacio','baffo','bagno','balia','balla','balli','ballo','banca','barba','barca','basta','basso','bella','belle','belli','bello','bevve','bisogno','bocca','bordo','borsa','bosco','botte','brace','brano','breve','brina','brodi','brodo','bruna','bruno','bucce','buchi','buona','buoni','buono','burro',
    'calza','calze','calzo','campi','campo','canta','canti','canto','capra','carbone','carro','carta','carte','casse','cassa','cassi','catena','cause','cavi','cavo','cedere','celeste','censo','cenni','cento','cerca','cerchi','cerco','certa','certe','certi','certo','cesto','chiave','chiesa','china','chino','cibo','cieco','cielo','cifre','cima','cinta','cinto','circa','citta','classe','codice','coffa','colla','colpa','colpe','colpi','colpo','conta','conte','conti','conto','copia','copre','copri','corda','corno','corpo','corre','corri','corso','corsa','corte','corti','corto','cosce','cosi','costa','coste','costi','costo','crema','creta','crisi','cross','crosta','crudo','cubo','cumulo','cupa','cura','curva',
    'darai','dare','degli','degna','degni','degno','dello','denso','dente','denti','desta','detto','dieci','dieta','dimmi','dipinto','dirsi','disco','dittero','divan','divano','dolce','dolci','donna','donne','dopo','dorme','dormi','dormo','dosso','dovevo','dovrei','dramma','duomo','dunque','duomo','durre','durre',
    'erano','erede','eredi','ermo','erma','erotico','errore','esame','esami','esempio','esisto','esito','essere','estra','etica','etico','euro','eva','evita',
    'fabbri','facce','faccia','facile','falsa','falsi','falso','farsa','farsi','fascia','fasti','fatto','fave','febbri','febbre','felci','felice','feltro','femori','fermi','fermo','feroce','fertili','festa','feste','fetta','feudi','feudo','fibra','fibre','fiele','figli','figlie','figlio','fila','file','film','filtro','finire','finita','finito','fiocco','fiore','fiori','firma','firme','fisica','fisico','fissa','fissi','fisso','fiume','fiumi','focene','foglia','foglio','folla','folli','folle','folto','fonda','fonde','fondi','fondo','fonte','forca','forco','forma','forme','forno','forni','forse','forte','forti','forza','forze','fossa','fosse','fossi','fosso','fragole','frase','frasi','fredda','freddo','freni','freno','fresca','freschi','fresco','frutta','frutti','frutto','fuggi','fummo','funghi','fungo','funi','fuoco','furto','fusto','futuro',
    'gaffe','gaiar','gallo','galli','galla','galle','gamba','gambe','gambo','gambi','gara','gare','gatta','gatte','gatti','gatto','gemma','gemme','genio','genti','gente','genio','gergo','gesti','gesto','gesso','gioca','gioco','giochi','gioia','giorno','girare','girato','giro','giri','gitto','giusti','giusto','giura','giusto','glice','globo','globi','glori','gnomi','gnomo','goccia','gocce','goder','gomma','gomme','gonfia','gonfio','gonna','gonne','grado','gradi','grand','grano','grani','grasso','grato','grati','grave','gravi','grazia','grazie','greca','greci','greco','greve','greve','grezzo','grida','gridi','grido','grigi','grigia','grigio','grilli','grosso','grotta','grotte','grumo','grupp','guardo','guida','guide','guido','gusto','gusti','gusta',
    'identi','idilli','idolo','imano','imito','impari','impeto','indio','infame','infine','inizio','inviare','iride','iridi','irrigare','irisi','isola','isole','istinto','italia','itinerari',
    'labbra','labbro','laggi','laghi','lampi','lampo','lapis','larga','larghi','largo','latte','laude','laudi','lazzi','lecca','legge','leggi','legna','legno','lente','lenti','leone','leoni','leopardo','lepre','lepri','lesto','letto','letti','letta','libra','libri','libro','lieta','liete','lieto','lievi','lieve','limpidi','linea','linee','lingue','lirico','lirici','lista','liste','livre','locale','logo','logica','logico','lombi','lontana','lontane','lontano','losche','lotta','lotte','lotti','lotto','luglio','lunga','lunghi','lungo','lupo','lutto',
    'macchia','macchie','madre','madri','maga','maghi','maglia','magma','magna','magni','magno','mago','mai','maiale','malato','male','mali','mama','mamma','mancia','mandi','mando','mango','manna','manto','manzo','mappa','mappe','marca','marche','margine','marina','marini','marino','marmo','marmi','marra','marsa','marte','massa','masse','massi','masso','matti','matto','mazza','medaglia','medico','melo','melone','membro','memoria','meno','mensa','menta','mente','menti','mento','mercato','merci','mese','mesi','meta','meteora','metro','metri','mette','metti','mezzi','mezzo','mille','mio','miopia','mira','miraggio','misero','missione','misti','misto','misura','misure','mite','mitra','moglia','moglie','mogli','molla','molli','molto','molti','molta','molte','monda','mondi','mondo','monte','monti','moralme','mosca','mosse','motel','mucca','mucche','musi','muso','muschi','muschio','musica','muta','muto',
    'nanna','nappa','nasce','nasci','nasco','naso','nasso','nasti','nasti','natale','nato','natura','naufrago','navigo','nebbia','negli','negro','nemico','nervo','nervi','neutro','nidi','niente','nipote','nodo','nodi','noia','nomignolo','nonno','nonne','nonni','nordica','nordico','norma','nostra','nostri','nostro','nota','note','notte','notti','nove','novel','novella','nube','nudo','nuora','nuoto','nuova','nuovo','nuovi','nuove',
    'oasi','obesi','obeso','occhi','occhio','offesi','offeso','offra','offro','oggi','oggetto','oltre','ombra','ombre','omero','onda','onde','onestamente','operazione','opera','opere','opzione','opzioni','orata','orazione','orchidea','ordine','ordini','ore','orecchio','orecchie','orfana','orfano','orgoglio','origine','orina','orma','orme','oro','orribile','orso','orsi','ortodossa','orzo','oscar','oscena','ospite','ossesso','osteria','osti','otto','oste',
    'pacchi','padre','padri','paese','paesi','paga','paghi','pagina','pagine','palco','pallido','pallone','palmo','panda','panini','panino','panna','panne','papa','papesso','para','paradiso','parchi','parlo','parmig','parodia','parola','parole','parte','parti','partito','passi','passo','pasti','pasto','patata','patto','patti','paura','paure','pausa','pavone','peccato','pelle','pelli','pelo','peli','penna','penne','pensa','pensi','penso','pepe','pera','pere','pere','perdi','perdo','perno','pero','pesca','pesce','pesci','peschi','peso','pesi','pesta','peste','pettine','pettini','petto','pezzi','pezzo','piace','piaci','piano','pianta','pianti','pianto','piatto','piede','piedi','pieno','pietra','pietre','pigra','pigro','pinza','pioggia','pioppo','pipa','pipe','piscina','pista','piste','pittore','piuma','piume','pizza','pizze','plana','plani','plano','poesia','pollo','polli','polo','poltrone','polvere','pompa','pompe','ponte','ponti','popoli','popolo','porco','porge','porge','porga','porra','porre','porta','porte','porti','porto','posa','posto','posti','potere','povera','povere','poveri','povero','pozzi','pozzo','prati','prato','preda','preghi','prego','prele','prende','prendi','presa','prese','presi','preso','pretendere','pretendere','prezzi','prezzo','prima','primi','primo','prime','priva','privo','privi','prive','prodi','prodi','profondi','prole','prona','pronto','prosa','prossimi','provi','provo','prove','prozii','prozio','prozia','prua','prude','psiche','pugno','pulci','pulce','punte','punti','punto','punta','pura','puzze','puzzo',
    'quadra','quadri','quadro','qualche','quali','quasi','quei','quel','questa','questi','queste','questo','quota','quote','quoti','quote','quote',
    'rabbia','radici','radio','raffi','raffica','ragazza','ragazze','ragazzi','ragazzo','rage','ragna','ragni','ragno','rallenti','rame','rana','rane','rara','rare','raro','reato','reato','reazione','reggi','regna','regni','regno','regola','regole','relazione','remi','remo','rendi','rendo','rene','reni','resa','rese','resi','resta','reste','resti','resto','rete','reti','retti','retto','rial','riba','ribelle','riccio','riccia','ricca','ricche','ricchi','ricco','ricerca','ricetta','ride','ridi','rido','riempi','rifare','riforma','rifugio','riguardo','rilegga','rilevo','rilevi','rilevo','rima','rime','rimo','rincorso','ripensa','rischia','rischio','riso','risi','risorse','rispetto','risuona','ritmi','ritmo','rivoluzione','roba','robot','rocce','roccia','rogni','rogno','roma','romanzo','romba','rombi','rombo','roca','roca','rosa','rose','rosso','rotaie','rotaie','rotti','rotto','rotta','rovine','ruba','rubo','rubi','rudi','rudimento','ruga','rughe','rumori','rumore','ruolo','ruoli','rurale','russa','russe','russi','russo','rustico',
    'sabbia','sacchi','sacco','sacra','sacre','sacri','sacro','saggi','saggio','sai','sala','salame','sale','salgo','sali','salsa','salse','salse','salta','saluti','saluto','sana','sano','sapere','sapevo','sapone','santa','santi','santo','sante','sapere','sapore','sapori','sarai','sarebbe','sarmenti','sarta','sarto','sartoria','sasso','sata','savia','savio','sazia','sazi','sazio','sbagli','sbaglio','sbocco','scala','scale','scaltri','scaltro','scappa','scappi','scarpa','scarpe','scarso','scelti','scemo','sceso','scese','scia','sciatore','scienze','sciopero','scolaro','scoperta','scopo','scoprire','scorso','scrivere','scuola','scuole','scuro','scuri','sdraio','secco','secchi','secchio','secondo','secondi','sedere','sedie','segna','segni','segno','segue','segui','seguo','sembra','seme','semi','sempre','senno','seno','sensi','senso','sento','senza','serpe','serpi','serra','serve','servi','servo','sesso','seta','sete','sette','sguardi','sguardo','siamo','sicura','sicuri','sicuro','signora','signore','signori','signor','silenzio','simile','simili','simulo','sincero','siti','sito','smeraldo','smetti','smetto','snella','snello','snobs','sobrio','sociali','sociale','soffi','soffio','soffre','sogni','sogno','solo','solare','solido','solita','solite','soliti','solito','somma','somme','sonno','sopra','sorgo','sorgi','sorpresa','sosti','sosta','sotto','sovrano','spada','spade','spago','spago','spaghi','spagne','spagna','spalla','spalle','sparare','sparare','spauri','spazi','spazio','spazzino','spazzole','speci','specie','speranza','spese','speso','spesa','spesso','spiare','spiega','spiego','spina','spine','spinto','spinte','sport','sposa','sposi','sposo','sposare','sprecato','spruzza','spruzzi','sputo','squilla','stadi','stadio','stalle','stampa','stampe','stanze','stanza','stare','starai','stati','stato','stata','state','stelle','stella','stenta','stesso','stessa','stessi','stivali','stoffa','stop','storia','storie','strada','strade','strane','strana','strani','strano','straordinario','straccio','striscia','striscio','strumenti','strumento','studi','studio','stupido','sua','sue','suo','suoi','sugo','suolo','suono','suoni','suora','suore','super','sussurro','svago','sveglia','svelti','svelto','svenire','svenuto','svolta','svolte',
    'tabella','tabelle','tabacco','taccia','taccio','taglia','taglio','talora','tamburo','tana','tane','tantra','tanto','tante','tanti','tante','tappe','tappa','targhe','tarocco','tasca','tasche','tassa','tasse','tasso','tasti','tasto','tatto','tavoli','tavolo','tavole','teatro','tecnico','tela','telai','tema','temere','tempo','tempi','tendi','tendo','tenere','tener','tenuta','teorica','teoria','terra','terre','terzo','testa','teste','testi','testo','tetro','tetto','tibia','tigre','tigri','timore','timori','tinta','tinte','tinti','tipico','tirare','titolo','tizio','tocca','toccare','tocco','tolto','tomba','tombe','tondo','tonda','tondi','tonde','tonno','tono','toni','toppe','torba','torce','torchio','tornare','torta','torte','torti','torto','tosse','tovaglia','traccia','tragica','traino','trapano','trama','trame','tratta','tratto','tre','treno','treni','trono','troppo','trova','trovo','trovi','trovai','truppe','truppa','tubo','tubi','tuoni','tuono','turbe','turba','turno','turni','tutta','tutte','tutti','tutto','tuttavia',
    'uccelli','uccello','udimmo','udito','uditi','uffici','ufficio','ufa','ugual','uguali','uguale','uguaglianza','ulivi','ulivo','ulteriori','ulteriore','ultime','ultimi','ultimo','ululato','umana','umani','umano','umile','umili','umore','unghie','unghia','uniche','uniti','unito','unite','unita','urlare','urtare','usanze','usanza','usare','usata','usati','usate','usato','uscio','uscita','utili','utile','uva','uve',
    'vacche','vacanze','vacanza','vacca','valida','valido','valido','valli','vallo','valori','valore','valuta','vampa','vapor','vapore','vari','varia','varie','vario','vasta','vasto','vecchi','vecchia','vecchio','vedere','vedo','vedi','vedete','veduta','vegan','velata','velato','velina','vela','veloce','velocit','vendita','vendo','venni','vento','venti','venti','verbo','verde','verdi','verge','versa','versi','verso','verita','verme','vermi','vero','vespa','vespe','veste','vesti','vestiti','vestito','vetro','vetri','vetro','via','vie','viaggi','viaggio','vibra','vicina','vicine','vicini','vicino','vide','videro','vincere','vince','vinco','vino','vinto','vinti','viola','viole','virgola','virtu','viscido','vista','viste','visto','visi','viso','vivono','vivere','vivente','voce','voci','voglie','voglia','voglio','volere','voli','volo','volpe','volpi','volta','volte','volto','volumi','volume','voti','voto','vuole','vuota','vuoto',
    'zampa','zampe','zanzara','zona','zone','zoppo','zucca','zucche','zuppa','zuppe'
  ],
  en: [
    // 3 lettere
    'arm','art','ask','bad','bag','ban','bar','bat','bay','bed','bee','big','bit','box','boy','bug','bus','but','buy','cab','cam','cap','car','cat','cup','cut','dad','day','den','dim','dip','dog','dot','dry','due','ear','eat','egg','end','era','eve','fan','far','fat','few','fig','fin','fit','fix','fly','fog','for','fox','fry','fun','gas','gem','get','god','got','gun','gut','guy','had','ham','has','hat','her','hey','him','his','hit','hot','how','hub','ice','ill','ink','jam','jar','jaw','jet','job','jog','joy','key','kid','kit','lab','lad','lap','law','lay','leg','let','lid','lie','lip','log','low','mad','man','map','mat','may','men','mid','mix','mob','mom','mud','net','new','nod','not','now','nut','oak','oar','off','oil','old','one','our','out','owe','owl','own','pad','pal','pan','pat','paw','pay','pea','pen','per','pet','pie','pig','pin','pit','pop','pot','pub','put','rag','ran','rat','raw','red','rib','rid','rim','rip','rod','row','rub','rug','run','sad','sat','saw','say','sea','see','set','sew','she','shy','sin','sip','sir','sit','six','ski','sky','sly','son','spa','spy','sum','sun','tab','tag','tan','tap','tar','tax','tea','ten','the','tie','tin','tip','toe','too','top','toy','try','tub','two','use','van','vet','vow','war','was','way','web','wed','wet','who','why','wig','win','wit','woe','won','yes','yet','you','zip',
    // 4 lettere
    'able','aces','ache','acid','acre','acts','adds','ages','aide','aids','aims','airs','ales','ally','also','ants','apes','apex','area','arms','army','arts','asks','atom','aunt','auto','away','axes',
    'baby','back','bade','bags','bait','bake','bald','bale','ball','balm','band','bane','bang','bank','bans','bare','bark','barn','bars','base','bash','bask','bath','bats','bays','bead','beak','beam','bean','bear','beat','beds','beef','been','beer','bees','begs','bell','belt','bend','bent','best','bets','bias','bide','bids','bike','bile','bill','bind','bins','bird','bite','bits','blew','blob','blot','blow','blue','blur','boar','boat','body','bogs','boil','bold','bolt','bomb','bond','bone','bong','book','boom','boon','boor','boot','bore','born','boss','both','bout','bowl','bows','boys','brag','bran','brat','bray','brew','brim','brow','buck','buds','buff','bugs','bulb','bulk','bull','bump','buns','burl','burn','burp','burr','bury','bush','bust','busy','butt','buys','buzz','byes','byte',
    'cabs','cafe','cage','cake','calf','call','calm','came','camp','cane','cans','cape','caps','card','care','carp','cars','cart','case','cash','cask','cast','cats','cave','cell','cent','chap','chat','chef','chew','chin','chip','chop','city','clad','clam','clan','clap','claw','clay','clip','clod','clog','clot','club','clue','coal','coat','code','cods','coil','coin','coke','cold','colt','coma','comb','come','cone','cons','cook','cool','coop','cope','copy','cord','core','corn','cost','cots','cove','cows','crab','crag','cram','crap','crew','crib','crop','crow','crud','cube','cubs','cued','cues','cuff','cull','cult','cups','curb','curd','cure','curl','curt','cuss','cute','cuts','cyst',
    'dads','daft','dais','dale','dame','damn','damp','dams','dare','dark','darn','dart','dash','data','date','daub','dawn','days','daze','dead','deaf','deal','dean','dear','debt','deck','deed','deem','deep','deer','defy','dell','demo','dens','dent','deny','desk','dial','dice','died','dies','diet','digs','dike','dime','dine','ding','dins','dint','dips','dire','dirt','disc','dish','disk','dive','dock','docs','does','doff','dogs','dole','doll','dome','done','dons','doom','door','dope','dorm','dose','doss','dote','dots','dour','dove','down','drab','drag','dram','draw','dray','drew','drip','drop','drug','drum','dual','dubs','duct','dude','duds','duel','dues','duet','duke','dull','dumb','dump','dune','dunk','duns','duos','dupe','dusk','dust','duty','dyed','dyer','dyes',
    'each','earl','earn','ears','ease','east','easy','eats','ebbs','echo','eddy','edge','edit','eels','eery','eggs','egos','elks','ells','elms','else','emit','ends','envy','epic','eras','errs','etch','even','ever','eves','evil','exam','exit','eyed','eyes',
    'face','fact','fade','fads','fail','fain','fair','fake','fall','fame','fang','fans','fare','farm','fast','fate','fats','fawn','fays','faze','fear','feat','feds','feed','feel','fees','feet','fell','felt','fend','fens','fern','fest','feud','fiat','figs','file','fill','film','find','fine','fins','fire','firm','firs','fish','fist','fits','five','flag','flak','flan','flap','flat','flaw','flax','flay','flea','fled','flee','flew','flex','flip','flit','flop','flow','flue','flux','foal','foam','foes','fogs','foil','fold','folk','fond','font','food','fool','foot','ford','fore','fork','form','fort','foul','four','foxy','frat','fray','free','fret','frog','from','fuel','full','fume','fund','funk','furl','furs','fury','fuse','fuss','fuzz',
    'gabs','gads','gaff','gage','gags','gain','gait','gala','gale','gall','game','gang','gape','gaps','garb','gash','gasp','gate','gave','gays','gaze','gear','geek','gees','geld','gels','gems','gene','gent','gets','gibe','gift','gigs','gild','gill','gilt','gins','gird','girl','gist','give','glad','glee','glen','glib','glob','glow','glue','glum','glut','gnat','gnaw','goad','goal','goat','gobs','gods','goer','goes','gold','golf','gone','gong','good','goof','goon','goop','gore','gory','gosh','gout','gown','grab','gram','gran','gray','grew','grey','grid','grim','grin','grip','grit','grog','grow','grub','gulf','gull','gulp','gums','guns','guru','gush','gust','guts','guys','gyms',
    'hack','hags','hail','hair','hake','hale','half','hall','halo','halt','hams','hand','hang','hank','hard','hare','hark','harm','harp','hart','hash','hasp','hate','hats','haul','have','hawk','hays','haze','hazy','head','heal','heap','hear','heat','heck','heed','heel','heft','heir','held','hell','helm','help','hemp','hems','hens','herb','herd','here','hero','hers','hews','hick','hide','high','hike','hill','hilt','hind','hint','hips','hire','hiss','hits','hive','hoax','hobo','hobs','hock','hods','hoes','hogs','hold','hole','holy','home','hone','honk','hoof','hook','hoop','hoot','hope','hops','horn','hose','host','hour','hove','howl','hubs','hued','hues','huff','huge','hugs','hula','hulk','hull','hump','hums','hung','hunk','hunt','hurl','hurt','hush','husk','hymn','hype',
    'ibis','iced','ices','icon','idea','ides','idle','idly','idol','imps','inch','info','inks','inns','into','ions','iota','iris','irks','isle','itch','item',
    'jabs','jack','jade','jail','jamb','jams','jars','jaws','jays','jazz','jeep','jeer','jell','jerk','jest','jets','jibe','jigs','jilt','jinx','jive','jobs','jock','jogs','join','joke','jolt','josh','jots','jowl','joys','judo','jugs','juke','jump','junk','jury','just','jute',
    'kale','keel','keen','keep','kegs','kelp','kept','keys','kick','kids','kill','kiln','kilo','kilt','kind','king','kink','kins','kiss','kite','kith','kits','kiwi','knee','knew','knit','knob','knot','know',
    'labs','lace','lack','lacy','lads','lady','lags','laid','lain','lair','lake','lamb','lame','lamp','lams','land','lane','laps','lard','lark','lash','lass','last','late','lath','laud','lava','laws','lays','laze','lazy','lead','leaf','leak','lean','leap','leas','leek','leer','lees','left','legs','lend','lens','lent','less','lest','lets','levy','lewd','liar','lice','lick','lids','lied','lien','lies','lieu','life','lift','like','lilt','lily','limb','lime','limn','limo','limp','line','link','lint','lion','lips','lira','lire','lisp','list','lite','live','load','loaf','loam','loan','lobe','lobs','lock','loco','lode','loft','logs','loin','loll','lone','long','look','loom','loon','loop','loot','lope','lord','lore','lose','loss','lost','lots','loud','lout','love','lows','luau','lube','luck','luge','lugs','lull','lump','lung','lure','lurk','lush','lust','lute','lyes','lynx','lyre',
    'mace','made','mads','mage','magi','maid','mail','maim','main','make','male','mall','malt','mama','mane','mans','many','maps','mare','mark','mars','mart','mash','mask','mass','mast','mate','math','mats','maul','maws','maxi','maze','mead','meal','mean','meat','meds','meek','meet','meld','melt','memo','mend','mens','menu','meow','mere','mesa','mesh','mess','mete','mews','mica','mice','midi','mien','miff','mike','mild','mile','milk','mill','mils','mime','mind','mine','mini','mink','mint','minx','mire','miry','miss','mist','mite','mitt','moan','moat','mobs','mock','mode','mods','moil','mold','mole','moll','molt','monk','mood','moon','moor','moos','moot','mope','mops','more','morn','moss','most','mote','moth','move','mown','mows','much','muck','muds','muff','mugs','mule','mull','muse','mush','musk','muss','must','mute','mutt','myth',
    'nabs','nags','nail','name','nape','naps','nard','nary','nave','navy','nays','near','neat','neck','need','neon','nest','nets','news','newt','next','nibs','nice','nick','nigh','nine','nips','nits','nobs','node','nods','noel','none','nook','noon','nope','norm','nose','nosy','note','noun','nova','nubs','nude','nuke','null','numb','nuns','nuts',
    'oars','oath','oats','obey','oboe','odds','odes','odor','ogle','ogre','oils','oily','oink','okay','okra','olds','oleo','omen','omit','once','ones','only','onto','oohs','oops','ooze','oozy','opal','open','opts','opus','oral','orbs','orca','ores','orgy','ouch','ours','oust','outs','oval','oven','over','owed','owes','owls','owns','oxen','oxes',
    'pace','pack','pact','pads','page','paid','pail','pain','pair','pale','pall','palm','pals','pane','pang','pans','pant','papa','pard','pare','park','pars','part','pass','past','pate','path','pats','pave','pawl','pawn','paws','pays','peak','peal','pear','peas','peat','peck','peek','peel','peep','peer','pegs','peke','pelt','pens','peon','perk','perm','pert','peso','pest','pets','pews','phew','pick','pied','pier','pies','pigs','pike','pile','pill','pimp','pine','ping','pink','pins','pint','pion','pipe','pips','pita','pith','pity','plan','plat','play','plea','pled','plod','plop','plot','plow','ploy','plug','plum','plus','pock','pods','poem','poet','pogo','poke','poky','pole','poll','polo','pomp','pond','pone','pong','pons','pony','pooh','pool','poop','poor','pope','pops','pore','pork','porn','port','pose','posh','post','posy','pots','pouf','pour','pout','prat','pray','prep','prey','prig','prim','prod','prof','prom','prop','pros','prow','pubs','puck','puff','pugs','puke','pull','pulp','puma','pump','punk','puns','punt','puny','pups','pure','purl','purr','push','puss','puts','putt','pyre',
    'quad','quay','quid','quip','quit','quiz',
    'race','rack','racy','raft','rage','rags','raid','rail','rain','rake','ramp','rams','rang','rank','rant','rape','rapt','rare','rash','rasp','rate','rats','rave','raws','rays','raze','razz','read','real','ream','reap','rear','redo','reds','reed','reef','reek','reel','refs','rein','reps','rest','revs','rice','rich','rick','ride','rids','rife','riff','rift','rigs','rile','rill','rime','rims','ring','rink','riot','ripe','rips','rise','risk','rite','road','roam','roan','roar','robe','robs','rock','rode','rods','roes','roil','role','roll','romp','roof','rook','room','root','rope','rose','rosy','rote','rout','rove','rows','rube','rubs','ruby','ruck','rude','rued','rues','ruff','rugs','ruin','rule','rump','runs','runt','ruse','rush','rust','ruts',
    'sack','sacs','safe','saga','sage','sago','sags','said','sail','sake','sale','salt','same','sand','sane','sang','sank','sans','saps','sari','sash','sass','sate','save','sawn','saws','says','scab','scad','scam','scan','scar','scat','scot','scow','scud','scum','seal','seam','sear','seas','seat','sect','seed','seek','seem','seen','seep','seer','sees','self','sell','semi','send','sent','sept','sets','sewn','sews','sexy','shag','sham','shed','shes','shew','shim','shin','ship','shoe','shoo','shop','shot','show','shun','shut','sick','side','sift','sigh','sign','silk','sill','silo','silt','sine','sing','sink','sins','sire','sirs','site','sits','size','skat','skew','skid','skim','skin','skip','skis','skit','slab','slag','slam','slap','slat','slaw','slay','sled','slew','slid','slim','slip','slit','slob','sloe','slog','slop','slot','slow','slug','slum','slur','slut','smit','smog','smug','smut','snag','snap','snip','snit','snob','snot','snow','snub','snug','soak','soap','soar','sobs','sock','soda','sods','sofa','soft','soil','sold','sole','solo','sols','some','sons','soon','soot','sops','sore','sort','sots','soul','soup','sour','sown','sows','soya','soys','spam','span','spar','spas','spat','spec','sped','spew','spin','spit','spot','spry','spud','spun','spur','stab','stag','star','stat','stay','stem','step','stew','stir','stop','stow','stub','stud','stun','stye','subs','such','suck','suds','sued','suer','sues','suet','suit','sulk','sumo','sump','sums','sung','sunk','sups','sure','surf','suss','swab','swag','swam','swan','swap','swat','sway','swig','swim','sync',
    'tabs','tack','tact','tads','taco','tags','tail','take','tale','talk','tall','tame','tamp','tans','tape','taps','tare','tarn','taro','tarp','tars','tart','task','tats','taut','taxi','teak','teal','team','tear','teas','teat','tech','teem','teen','tees','tell','temp','tend','tens','tent','term','tern','test','text','than','that','thaw','thee','them','then','they','thin','this','thru','thud','thug','thus','tick','tics','tide','tidy','tied','tier','ties','tiff','tile','till','tilt','time','tine','ting','tins','tint','tips','tire','tits','toad','toed','toes','tofu','toga','togs','toil','told','toll','tomb','tome','tone','tong','tons','tony','took','tool','toot','tops','tore','torn','tors','tort','toss','tote','tots','tour','tout','town','tows','toys','tram','trap','tray','tree','trek','trim','trio','trip','trod','trot','true','tsar','tubs','tuck','tuft','tugs','tuna','tune','turf','turn','tusk','tuts','twig','twin','twit','type','typo',
    'ugly','ulna','undo','unit','unto','upon','urge','urns','used','user','uses',
    'vain','vamp','vans','vase','vast','vats','veal','veer','veil','vein','vend','vent','verb','very','vest','veto','vets','vial','vice','vide','vied','vies','view','vile','vine','vino','viny','viol','visa','vise','vita','void','vole','volt','vote','vows',
    'wack','wade','wads','waft','wage','wags','wail','wait','wake','wale','walk','wall','wand','wane','want','ward','ware','warm','warn','warp','wars','wart','wary','wash','wasp','watt','wave','wavy','waxy','ways','weak','weal','wean','wear','webs','weds','weed','week','weep','weft','weir','weld','well','welt','wend','went','wept','were','west','what','when','whew','whey','whim','whip','whir','whit','whiz','whoa','whom','whop','wick','wide','wife','wigs','wild','will','wilt','wily','wimp','wind','wine','wing','wink','wins','wino','wipe','wire','wiry','wise','wish','wisp','with','wits','woes','woke','wolf','woks','wold','womb','wont','wood','woof','wool','woos','word','wore','work','worm','worn','wrap','writ',
    'yack','yams','yank','yaps','yard','yarn','yawl','yawn','yaws','year','yeah','yegg','yell','yelp','yens','yeti','yews','yips','yoga','yogi','yoke','yolk','yore','your','yowl','yule','yups','yurt',
    'zany','zaps','zeal','zebu','zero','zest','zinc','zing','zips','zits','zone','zoom',
    // 5+ lettere
    'about','above','actor','added','admit','adult','after','again','agent','agree','ahead','album','alert','alien','alike','alive','allow','alone','along','aloud','altar','amaze','amber','angel','anger','angle','angry','ankle','apart','apple','apply','arena','argue','arise','armed','aroma','arose','arrow','aside','asked','asset','avoid','awake','aware','awful',
    'badge','badly','baker','balls','bands','banjo','barge','basic','basin','basis','batch','beach','beads','beams','beans','bears','beast','beech','being','below','bench','berry','black','blade','blame','blank','blast','blaze','bleak','bleed','blend','bless','blind','block','blood','bloom','blown','blues','blunt','board','boast','bonds','bonus','books','boots','booth','bored','boxer','brain','brake','brand','brass','brave','bread','break','breed','brick','bride','brief','bring','broad','broke','brown','brush','build','built','burns','burst','buyer',
    'cabin','cable','candy','canoe','cargo','carry','carve','catch','cause','cease','chain','chair','chalk','champ','chant','charm','chart','cheap','cheat','check','cheek','cheer','chess','chest','chief','child','chili','china','chips','chord','civil','claim','clamp','clash','class','clean','clear','clerk','click','cliff','climb','cling','clock','close','cloth','cloud','clown','coach','coast','color','comma','comic','comma','coral','corps','couch','count','court','cover','crack','craft','crane','crash','crate','crawl','crazy','cream','creek','crepe','crest','crew','cried','crime','crisp','cross','crowd','crown','crude','crush','crust','cubic','curse','curve','cycle',
    'daily','dairy','dance','dared','dates','dealt','death','debit','debut','decay','decoy','deeds','delay','delta','depth','dingo','dirty','ditch','diver','dives','dizzy','dodge','doing','donut','doors','doubt','dough','dozen','draft','drain','drama','drank','dream','dress','dried','drift','drill','drink','drive','drone','drove','drown','drugs','drums','drunk','dryer',
    'eager','eagle','early','earth','eaten','eight','elect','elite','empty','enact','ended','enemy','enjoy','enter','entry','equal','error','essay','event','every','exact','exile','exist','extra',
    'fable','faces','faded','faint','faith','false','famed','farms','fault','feast','fence','fever','field','fifth','fifty','fight','final','finds','fires','first','fixed','flame','flash','flask','fleet','flesh','flies','flint','float','flock','flood','floor','flora','flour','flown','fluid','flute','focus','foggy','folks','foods','foray','force','forge','forgo','forks','forms','forth','forty','found','foxes','frame','frank','fraud','fresh','front','frost','fruit','fully','funds','funny',
    'gains','games','gamma','gauze','gaped','gases','gauge','gears','geese','genie','genre','gents','germs','ghost','giant','gifts','gives','glade','glare','glass','gleam','glean','glide','globe','gloom','glory','glove','goals','goats','going','goofy','goose','gourd','grace','grade','grain','grand','grant','grape','graph','grasp','grass','grave','great','greed','green','greet','grief','grill','grime','gripe','groin','groom','gross','group','grout','grove','grown','growl','guess','guest','guide','guilt',
    'habit','hairy','halve','handy','happy','harsh','haste','hatch','hated','haunt','haven','havoc','hazel','heads','heart','heavy','hedge','helix','hello','helps','hence','herbs','heron','hertz','hides','hiker','hills','hindu','hippo','hired','hobby','hocks','hoist','holds','holly','homer','homes','honey','hooks','hoops','hoped','horde','horns','horse','hosts','hotel','hound','house','hover','human','humor','hunch','hurry','hyena','hymns',
    'ideal','idols','image','imply','incur','index','inert','infer','inlet','inner','input','intro','irate','irony','issue','ivory',
    'jaded','japan','jelly','jerky','jewel','jiffy','joint','joker','jolly','jolts','joust','judge','juice','juicy','jumbo','jumps','junky',
    'kayak','kebab','kelps','kicks','kicks','kinds','kings','kites','kitty','knack','knees','knelt','knife','knits','knock','knots','known','koala',
    'label','labor','laced','laden','lager','lakes','lance','lands','large','laser','later','laugh','layer','leads','leaks','leans','leaps','learn','lease','least','leave','ledge','leech','legal','lemon','level','lever','light','liked','limit','lined','links','lions','lists','liver','llama','loads','loaf','loans','lobby','local','locks','lodge','loins','loose','lords','lorry','loser','lover','lower','loyal','lucky','lumpy','lunar','lunch','lungs','lying','lyric',
    'macho','madam','major','maker','males','manga','manly','maple','march','marsh','match','maths','maxim','mayor','meals','means','meant','medal','media','melon','melts','mercy','merge','merit','merry','metal','meter','metro','mice','mighty','minds','miner','minor','minty','mirth','mists','mixed','mocha','model','modem','moist','molar','money','month','moods','moose','moral','motel','motet','motor','mount','mourn','mouse','mouth','moved','mover','movie','mower','muddy','music','mussy','muted',
    'nails','naked','named','names','nanny','nasal','naval','needs','nerve','never','newer','nicer','niche','nicks','niece','night','ninth','nodes','noise','noisy','nomad','north','nosed','noses','notch','noted','notes','novel','nudge','nurse',
    'oasis','obese','occur','ocean','octet','offer','often','olive','onion','onset','opera','opted','orbit','order','organ','other','otter','ought','ounce','outer','owing','owls','owned','owner','oxide',
    'paced','packs','pages','paint','pairs','panda','panel','panic','pansy','paper','parka','parks','parry','parts','party','pasta','paste','patch','paths','pause','peace','peach','pearl','pedal','penal','penny','peony','perch','peril','perky','petal','phase','phone','photo','piano','piety','piled','piles','pills','pilot','pinch','pinky','pints','pious','pipes','pitch','pivot','pixel','pizza','place','plain','plane','plank','plant','plate','plays','plaza','plead','pleas','plier','plots','plows','pluck','plumb','plume','poets','point','poked','polar','poles','polio','polka','ponds','pools','porch','poses','posit','posse','pouch','pound','pours','power','prank','prawn','prays','press','price','prick','pride','prime','print','prior','prism','prize','probe','prone','prong','proof','proud','prove','proxy','prune','psalm','pubic','puffy','pulse','punch','punks','pupil','puppy','puree','purge','purse','pussy','put',
    'quack','quail','quake','quart','queen','queer','query','quest','queue','quick','quiet','quill','quilt','quirk','quite','quote',
    'rabid','races','radar','radio','rafts','rains','raise','rally','ranch','range','ranks','rapid','rated','rates','ratio','raven','razor','reach','react','reads','ready','realm','rebel','rebut','recap','reedy','reeks','reels','refer','regal','reign','reins','rejig','relax','relay','remit','renew','rents','repay','reply','rerun','reset','resin','retry','reuse','rhino','rider','rides','ridge','rifle','right','rigid','rinse','riots','riper','risen','river','rivet','roads','roams','roast','robin','robot','rocks','rocky','rodeo','roger','rogue','roles','rolls','roman','romps','rooks','rooms','roost','roots','roped','ropes','roses','rough','round','roust','route','rover','rowdy','royal','ruby','rugby','ruler','rules','rumor','runny','runts','rural','rusty',
    'sable','sadly','safer','safes','sages','sails','saint','salad','sales','sally','salon','salsa','salts','salty','salute','sandy','sappy','sated','satin','satyr','sauce','saucy','sauna','saved','saver','saves','savor','scald','scale','scalp','scams','scant','scare','scarf','scary','scene','scent','scoff','scold','scoop','scoot','scope','score','scorn','scour','scout','scrap','screw','scrub','scuff','seals','seams','seats','sects','sedan','seedy','seeks','seems','seers','semis','sends','sense','seven','sever','sewed','sewer','shack','shade','shady','shaft','shake','shaky','shall','shame','shape','share','shark','sharp','shave','shawl','shear','sheds','sheep','sheer','sheet','shelf','shell','shied','shift','shine','shins','shiny','ships','shire','shirt','shock','shoes','shone','shook','shoot','shops','shore','short','shots','shout','shove','shown','shred','shrew','shrub','shrug','shuck','shunt','shuts','sibyl','sided','sides','siege','sigma','signs','silly','since','sinks','sired','sires','sites','sixth','sixty','sized','sizes','skate','skein','skews','skids','skied','skier','skies','skiff','skill','skimp','skins','skirt','skull','slack','slain','slang','slant','slash','slate','slave','sleek','sleep','sleet','slept','slice','slick','slide','slime','slimy','sling','slips','slits','slope','sloth','slots','slung','slunk','slush','small','smart','smash','smell','smelt','smile','smirk','smith','smoke','smoky','smote','snack','snail','snake','snaky','snare','snarl','sneak','sneer','sniff','snipe','snobs','snore','snort','snout','snowy','snubs','snuff','snugs','soaks','soaps','sober','socks','sofas','solar','soles','solid','solve','sonar','songs','sonic','sooty','sorry','sorts','souls','sound','soups','sours','south','space','spade','spare','spark','spasm','spawn','speak','specs','speed','spell','spelt','spend','spent','spice','spicy','spied','spies','spike','spill','spilt','spine','spiny','spire','spite','splat','split','spoil','spoke','spoof','spook','spool','spoon','spore','sport','spout','sprig','spurn','spurs','squad','squat','stack','staff','stage','stain','stair','stake','stale','stalk','stall','stamp','stand','stank','stare','stark','start','stash','state','stats','stave','stays','stead','steak','steal','steam','steed','steel','steep','steer','stems','steps','stern','stews','stick','stiff','still','stilt','sting','stink','stint','stir','stirs','stock','stoic','stoke','stole','stomp','stone','stony','stood','stool','stoop','stops','store','stork','storm','story','stout','stove','straw','stray','strip','strut','stubs','stuck','study','stuff','stump','stung','stunk','stuns','stunt','style','suave','sugar','suing','suite','suits','sulky','sumac','sunny','suns','super','supra','sutra','swabs','swamp','swank','swans','swarm','sways','swear','sweat','sweep','sweet','swell','swept','swift','swill','swims','swine','swing','swipe','swirl','swiss','swoon','swoop','sword','swore','sworn','synod','syrup',
    'table','taboo','tacit','tacky','taken','takes','talks','tally','talon','tamed','tamer','tango','taper','tapes','tardy','tares','tarot','tarry','taste','tasty','tatty','taunt','tawny','taxes','teach','teams','tears','teary','tease','teddy','teens','teeth','tempo','tempt','tense','tenth','tents','terms','tests','texts','thank','theft','their','theme','there','these','thick','thief','thigh','thing','think','third','those','three','threw','throb','throw','thumb','thump','tibia','tiara','tidal','tides','tiger','tight','tilde','tiled','tiles','tilts','timed','timer','times','tipsy','tired','tires','titan','title','toads','toast','today','toils','token','tonal','toned','tones','tonic','tools','tooth','topaz','topic','torch','total','toted','totem','touch','tough','tours','towed','towel','tower','towns','toxic','toxin','toyed','trace','track','tract','trade','trail','train','trait','tramp','traps','trash','trawl','trays','tread','treat','trees','trend','trial','tribe','trice','trick','tried','trill','trims','tripe','trips','troll','troop','trope','trout','trove','truce','truck','trump','trunk','trust','truth','tubas','tubed','tubes','tucks','tuned','tuner','tunes','tunic','turfs','turns','tutor','tweak','tweed','tweet','twice','twigs','twins','twirl','twist','tying','types','typos',
    'udder','ulcer','ultra','unbar','uncle','under','undid','undue','unfit','unify','union','unite','units','unity','until','upper','upset','urban','urged','usage','users','usher','using','usual','usury','utter',
    'vacuo','vague','vails','vales','valet','valid','value','valve','vapor','vault','vaunt','vegan','veils','veins','venom','venue','verbs','verge','verse','verso','very','vetch','vexed','viaduct','vicar','video','views','vigil','villa','vines','viola','viper','viral','virus','visas','visit','vital','vivid','vixen','vocab','vocal','vodka','vogue','voice','volts','vomit','voter','votes','vouch','vowed','vowel','vulva',
    'wacky','waded','wader','wafer','wager','wages','wagon','waist','waits','wakes','walks','walls','waltz','wands','waned','wants','wards','wares','warms','warns','warps','wars','wash','wasps','waste','watch','water','waved','waver','waves','waxed','waxes','weary','weave','wedge','weeds','weeks','weeps','weigh','weird','wells','welsh','wench','wends','whack','whale','wharf','wheat','wheel','where','which','whiff','while','whine','whips','whirl','whisk','white','whole','whose','widen','wider','widow','width','wield','wilds','willy','wimps','winch','winds','windy','wines','wings','winks','winos','wiped','wipes','wired','wires','wiser','wisps','witch','withe','wives','woken','woman','women','woods','woody','wools','woozy','words','wordy','works','world','worms','wormy','worry','worse','worst','worth','would','wound','woven','wraps','wrath','wreak','wreck','wrens','wrest','wring','wrist','write','writs','wrong','wrote','wrung','wryly',
    'yacht','yards','yarns','yeahs','years','yearn','yeast','yells','yelps','young','yours','youth',
    'zebra','zebus','zeros','zests','zincs','zings','zippy','zonal','zoned','zones','zooms'
  ]
};

// Sottoinsieme indicizzato per lunghezza usato da Word Ladder.
// Filtra automaticamente per garantire alfabeto/lunghezza coerenti.
function pickByLength(list, lang, len) {
  const allowed = ALPHABETS[lang].toLowerCase();
  return [...new Set(list.filter(w => w.length === len && [...w.toLowerCase()].every(c => allowed.includes(c))))];
}

export const LADDER_WORDS = {
  it: { 4: pickByLength(WORDS.it, 'it', 4) },
  en: { 4: pickByLength(WORDS.en, 'en', 4) }
};
